export const VLAJKY: Record<string, string> = {
  'Česko': 'https://flagcdn.com/w80/cz.png',
  'Slovensko': 'https://flagcdn.com/w80/sk.png',
  'Kanada': 'https://flagcdn.com/w80/ca.png',
  'USA': 'https://flagcdn.com/w80/us.png',
  'Rusko': 'https://flagcdn.com/w80/ru.png',
  'Finsko': 'https://flagcdn.com/w80/fi.png',
  'Švédsko': 'https://flagcdn.com/w80/se.png',
  'Německo': 'https://flagcdn.com/w80/de.png',
  'Švýcarsko': 'https://flagcdn.com/w80/ch.png',
  'Lotyšsko': 'https://flagcdn.com/w80/lv.png',
  'Dánsko': 'https://flagcdn.com/w80/dk.png',
  'Norsko': 'https://flagcdn.com/w80/no.png',
  'Rakousko': 'https://flagcdn.com/w80/at.png',
  'Francie': 'https://flagcdn.com/w80/fr.png',
  'Maďarsko': 'https://flagcdn.com/w80/hu.png',
  'Kazachstán': 'https://flagcdn.com/w80/kz.png',
  'Velká Británie': 'https://flagcdn.com/w80/gb.png',
  'Polsko': 'https://flagcdn.com/w80/pl.png',
  'Španělsko': 'https://flagcdn.com/w80/es.png',
  'Itálie': 'https://flagcdn.com/w80/it.png',
  'Anglie': 'https://flagcdn.com/w80/gb-eng.png',
  'Brazílie': 'https://flagcdn.com/w80/br.png',
  'Argentina': 'https://flagcdn.com/w80/ar.png',
  'Portugalsko': 'https://flagcdn.com/w80/pt.png',
  'Belgie': 'https://flagcdn.com/w80/be.png',
  'Nizozemsko': 'https://flagcdn.com/w80/nl.png',
  'Chorvatsko': 'https://flagcdn.com/w80/hr.png',
  'Mexiko': 'https://flagcdn.com/w80/mx.png',
  'Japonsko': 'https://flagcdn.com/w80/jp.png',
  'Jižní Korea': 'https://flagcdn.com/w80/kr.png',
  'Maroko': 'https://flagcdn.com/w80/ma.png',
  'Senegal': 'https://flagcdn.com/w80/sn.png',
  'Austrálie': 'https://flagcdn.com/w80/au.png',
  'Turecko': 'https://flagcdn.com/w80/tr.png',
  'Skotsko': 'https://flagcdn.com/w80/gb-sct.png',
  'Srbsko': 'https://flagcdn.com/w80/rs.png',
  'Slovinsko': 'https://flagcdn.com/w80/si.png',
  'Albánie': 'https://flagcdn.com/w80/al.png',
  'Rumunsko': 'https://flagcdn.com/w80/ro.png',
  'Gruzie': 'https://flagcdn.com/w80/ge.png',
  'Ukrajina': 'https://flagcdn.com/w80/ua.png',
  'Čína': 'https://flagcdn.com/w80/cn.png',
  'Nový Zéland': 'https://flagcdn.com/w80/nz.png',
};

export const LOGA: Record<string, string> = {
  'Real Madrid': 'https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg',
  'Manchester City': 'https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg',
  'Bayern Mnichov': 'https://upload.wikimedia.org/wikipedia/commons/1/1f/FC_Bayern_M%C3%BCnchen_logo_%28shield%29.svg',
  'PSG': 'https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg',
  'Barcelona': 'https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg',
  'Liverpool': 'https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg',
  'Chelsea': 'https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg',
  'Arsenal': 'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg',
  'Juventus': 'https://upload.wikimedia.org/wikipedia/commons/1/15/Juventus_FC_2017_icon_%28black%29.svg',
  'Inter Milán': 'https://upload.wikimedia.org/wikipedia/commons/0/05/FC_Internazionale_Milano_2021.svg',
  'AC Milán': 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Logo_of_AC_Milan.svg',
  'Atletico Madrid': 'https://upload.wikimedia.org/wikipedia/en/f/f4/Atletico_de_madrid_2017_logo.svg',
  'Borussia Dortmund': 'https://upload.wikimedia.org/wikipedia/commons/6/67/Borussia_Dortmund_logo.svg',
  'Ajax': 'https://upload.wikimedia.org/wikipedia/en/7/79/Ajax_Amsterdam.svg',
  'Porto': 'https://upload.wikimedia.org/wikipedia/en/3/3f/FC_Porto.svg',
  'Benfica': 'https://upload.wikimedia.org/wikipedia/en/a/a2/SL_Benfica_logo.svg',
  'HC Oceláři Třinec': 'https://upload.wikimedia.org/wikipedia/en/6/63/HC_Ocelari_Trinec.png',
  'HC Sparta Praha': 'https://upload.wikimedia.org/wikipedia/en/6/6c/HC_Sparta_Praha_logo.png',
  'HC Kometa Brno': 'https://upload.wikimedia.org/wikipedia/en/1/14/HC_Kometa_Brno.png',
  'HC Dynamo Pardubice': 'https://upload.wikimedia.org/wikipedia/en/3/3b/HC_Dynamo_Pardubice.png',
};

export function getObrazek(tym: string): string | null {
  return VLAJKY[tym] || LOGA[tym] || null;
}
